### ISSUE TITLE
Default unityVersion to the branch's m_EditorVersion in ProjectVersion.txt

### ISSUE THREAD

**Issue by dogboydog** [webbertakken/unity-builder#120]
I have working code (pretty simple) to read m_EditorVersion from ProjectSettings\ProjectVersion.txt. I'm using this as the input to `with: unityVersion`. Something like this could be the default if unityVersion is not specified. Any thoughts on that? Seems to be in keeping with the goal of having things work out of the box, but maybe you want to avoid parsing this file? Maybe in production people want to use a constant version to build binaries, but you'd think they'd be developing with that version too, right? It looks like the ProjectVersion.txt file has been around for a while (at least 2015), and is automatically updated by Unity when you upgrade. What do you think?

**Comment by webbertakken** [comment]
Hey @dogboydog,

I think it's an interesting idea.

Currently I think this is not desirable for three reasons:

- A change in CI pipeline should always be reflected in the CI configuration. Changing unity version is a major change in workflow. Therefor I would argue that automating version number for unity is semantically incorrect.
- Every change of version requires a separate license, which has to be acquired using a manual task (for personal licenses). This task specifically is currently not easy or desirable to automate.
- It would make the workflow not simpler but more complex to understand when working with matrices.

I think we should close this issue unless we have specific use cases that would require this.

**Comment by dogboydog** [comment]
Okay, I see what you mean and pretty much agree. 

> A change in CI pipeline should always be reflected in the CI configuration. Changing unity version is a major change in workflow. Therefor I would argue that automating version number for unity is semantically incorrect.

I'm not sure I fully understand this point, though.  

In my case, I have a separate CI pipeline that just makes sure the project can be tested and built with the version of Unity that is checked in. Everyone on the team is using whatever version is in ProjectVersion.txt for that branch. So if a developer updates Unity, Unity automatically changes the ProjectVersion.txt file. So either you keep the workflow exactly in step with ProjectVersion.txt (benefits: git history of the workflow file?), or the build is not using the same version you're developing with (may lead to unexpected results). The ProjectVersion.txt file itself is a record of the version for the project and it seems like Unity parses it to check compatibility. So I guess I see it as comparable to needing to re-specify the version of a dependency already declared in ` package.json`, but I could be wrong.

There's no deployment in this particular workflow, and also we have a non-free license. But I can see how this would be confusing or not useful in some cases like with a free license, so I agree it's probably not appropriate to default the version in this repo. 

However, it's easy to achieve without defaulting it in unity-builder anyway for anyone who would want to. Thanks!

**Comment by webbertakken** [comment]
Which part did you not understand exactly?

**Comment by dogboydog** [comment]
If you commit a change to ProjectVersion.txt, you are updating the Unity project, right?  Everyone that checks out the project will need to update. If you don't automate the version number, your options are to manually update the ./github/workflows/xxx.yml file with the same change, or not update it and have a version mismatch.  So why is semantically incorrect to use that version in automation if the developer's goal is to check that the project builds with the version of Unity that you are using in the project? Like imagine if this was an npm tool, and you used it CI. Would you expect the user to re-specify versions of dependencies that were specified in `package.json` in the CI code? Maybe you disagree with the comparison

**Comment by webbertakken** [comment]
I see.

Yes I think you will find that every production-grade project using nodejs will only change CI the nodejs version in CI when this is proven to work in the pipeline itself, not just when someone installs a different version of node and creates a commit.

Lets continue platform agnostic:

These things are semantically different because:

- Your CI pipeline is supposed to work all the time; it is the thing you rely on. A separate pull request is created when upgrading a version, and during this PR also documentation and contribution docs are changed and any incompatible parts will be fixed and from that moment on everyone works with that version. Note that in the review of this PR, people can comment on what is missing. Lastly, production deployment is probably tested right after or even before applying these changes, and from that moment on all features can be based on the new version; everyone rebases on a version that you know that works.
- Your development workflow on the other hand should contain as little hiccups as possible and everyone uses the same version. Nobody upgrades it without also performing the other tasks. If instead you would upgrade and implement a feature but conflict with other developers on their features then you have to manage this mismatch on a non-central location. This is where long-living forks and massive deltas start popping up.

The bigger a team is, the more important these differences become and in some cases entirely different teams are responsible for these two things. If you're saying my explanation isn't world-class I fully agree, but I'm not convinced we should change all Unity Actions based on 1 use case that in my opinion mixes concerns. (You'd have to come with objective reasons and why it would work for everyone else too).

If you want to do two semantically different things in the same step, this is possible of course. Nobody is stopping you from reading a file in a step before the build or test step and providing a value (using an output parameter) as the Unity version in Unity Builder and Unity Test Runner.

**Comment by dogboydog** [comment]
I'm in complete agreement after your replies that changing the behavior directly in these Unity actions isn't the right call and wasn't trying to argue that point anymore.  I was just curious of your reasoning for not recommending the practice even externally to these actions, which I understand better now. Thanks for taking the time.

**Comment by webbertakken** [comment]
You're very welcome
