### ISSUE TITLE
Wrong commit SHA on pull request 

### ISSUE THREAD

**Issue by RDeluxe** [webbertakken/unity-builder#147]
It seems that github.sha is not the commit actually triggering the workflow on a pull request, as described [here](https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286/2)

What that means is that the semantic versionning is then wrong : the number of commits and the commit SHA are both wrong.

This is not a major issue but it's kind of surprising if you use a "manual" local semantic versioning system, like we do. My editor tools tell me something and the builder something else.

https://github.com/webbertakken/unity-builder/blob/977683cd5ff023c7a8df7f4ad47623cdd5ed2158/src/model/versioning.js#L45

**Comment by webbertakken** [comment]
Hi @RDeluxe and thank you for reporting this,

Did you mean to write an issue for github actions themselves or for this repository specifically?
If we're talking about this repository, could you please elaborate how "semantic versioning is then wrong" and how the number of commits is wrong exactly? If this is the case we should definitely fix the issue.

**Comment by RDeluxe** [comment]
Hello 

Definitely for this repository.

The semantic versioning logic is not wrong per se. However I'm not sure it is the expected behaviour to have a version 0.3.40.xxxx locally and 0.3.41.yyyy during the build action.

If the workflow is triggered on a PR, the current commit is the merge commit, not the commit triggering the workflow.
So you have 1 more commit, and the SHA is not the same.

**Comment by webbertakken** [comment]
You're right! And that is indeed not desired behaviour.

So some history:

1. I remember having this error and fixing it by using `origin/branchName` as a reference for the amount of commits (with the correct outcome). 
2. This didn't work for tags, so that part was fixed [here](https://github.com/webbertakken/unity-builder/pull/92/files#diff-4d9bf5972dad4056ba9383617eaf9fcfR164-R167).
3. This didn't work for pull requests from external PRs, so that part was fixed [here](https://github.com/webbertakken/unity-builder/pull/105/files#diff-4d9bf5972dad4056ba9383617eaf9fcfR172), which most likely introduced the issue again.

If you know how to fix it properly (meaning working in all cases below) that would be great!

- pipeline triggered on push (happens when you commit or merge to master)
- pipeline triggered on internal pr (same repo)
- pipeline triggered on external pr (cross repo)
- pipeline triggered on tag (same repo)

**Comment by webbertakken** [comment]
Closing this as we don't have the manpower to solve minor issues like this and functionally it still works.

Solving this requires in depth knowledge of github actions and the watch checkout happens in detach head for different scenarios.
