### ISSUE TITLE
Android build fails with access denied error running Android SDK

### ISSUE THREAD

**Issue by chokoswitch** [webbertakken/unity-builder#167]
**Bug description**

When building with this action for Android, the build fails due to being unable to execute the Android SDK

`Win32Exception: ApplicationName='/opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager', CommandLine='--list', CurrentDirectory='/github/workspace/cafe-map/client/unity', Native error= Access denied`

**How to reproduce**

GitHub Action Run: https://github.com/curioswitch/curiostack/runs/1304213993?check_suite_focus=true
Workflow: https://github.com/curioswitch/curiostack/blob/master/.github/workflows/unity-build-cafemap.yml
Code: https://github.com/curioswitch/curiostack/tree/master/cafe-map/client/unity

**Expected behavior**

The build succeeds and an APK is created

**Additional details**

I tried running the command in docker locally

```
docker run -it --rm gableroux/unity3d:2019.4.12f1-android
/opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --list
```

and it works fine so surprised to see an access denied on the CI.

**Comment by GabLeRoux** [comment]
Known issue, https://gitlab.com/gableroux/unity3d/-/issues/85
We've been working on rebuilding and republishing all unity docker images with editors installed using `hub` instead of manual packages to solve this. Here's the new docker image repo: https://github.com/Unity-CI/docker

We also introduced a way for us to republish docker images without breaking previous builds using versions from the linked repo. This is some very recent work and could fail, but I suggest you give a try by specifying the new image as a custom image.

so in your case, switching form `gableroux/unity3d:2019.4.12f1-android` to an image found in here:  
https://hub.docker.com/r/unityci/editor/tags?page=1&name=2019.4.12f1-android

image versions will be documented shortly, but you could probably give a try to `unityci/editor:2019.4.12f1-android-0.3`. We also need to document the `customImage` parameter in unity-builder.

**Comment by GabLeRoux** [comment]
Also note that **you need to go through activation process again** if you use new images. Reason is that we now hardcoded the machine-id used by unity to activate. So when we move to these new images, upgrading from a version to another won't require a new license anymore.

**Comment by webbertakken** [comment]
Fixed in v2 alpha
