### ISSUE TITLE
'/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by ivan-omnidrone** [webbertakken/unity-builder#89]
We're seeing this error consistently. We have successfully setup the unity-test-runner, but are struggling with the builder. This message below is the only thing we see in the logs, the unity-builder step takes 1s to complete, so I would assume there are no Unity logs.

Note that our project is made of 2 sibling repos: _my-project-unity_ and _my-project-server_, both are folders in the root. We want to build _my-project-unity_, which inside contains the folders _Assets_, _ProjectSettings_ and _Packages_.

Any idea what's going on? Thanks!

        Run webbertakken/unity-builder@v0.15
          with:
            projectPath: my-project-unity 
            unityVersion: 2019.2.11f1
            targetPlatform: iOS
            buildMethod: MyNamespace.MyStaticMethodToBuild
          env:
            UNITY_EMAIL: ***
            UNITY_PASSWORD: ***
            UNITY_SERIAL: ***
        ##[warning]Error: The process '/usr/bin/git' failed with exit code 128
        ##[error]The process '/usr/bin/git' failed with exit code 128

**Comment by webbertakken** [comment]
@ivan-omnidrone Thanks a lot for reporting your issue with unity builder!

Technically it would be helpful if it were to give a little bit more output, so that is something to be improved.

To me it looks like the commands (that you find in `versioning.js` of this repo) can not find a git repository in the root of your project, as you have just checked out 2 repos in these folders. 

I believe this problem can be solved by running all the git commands in the folder that's specified using `projectPath`.

**Comment by webbertakken** [comment]
@ivan-omnidrone Could you try again with `unity-builder@3c040dd`?

**Comment by ivan-omnidrone** [comment]
Yes, it gave me this:

         Run webbertakken/unity-builder@3c040dd
          with:
            projectPath: my-project-unity
            unityVersion: 2019.2.11f1
            targetPlatform: iOS
            buildMethod: MyNamespace.MyStaticMethodToBuild
          env:
            UNITY_EMAIL: ***
            UNITY_PASSWORD: ***
            UNITY_SERIAL: ***
        ##[warning]Error: The process '/usr/bin/git' failed with exit code 1
         M .gitattributes
         M .github/PULL_REQUEST_TEMPLATE.md
         M .github/workflows/build.yml 
         M .gitignore
         M .gitmodules
         M .vscode/settings.json
         M Assets/.editorconfig
         M Assets/.gitignore
         ... [Bunch of other files from our repo]

        ##[error]Branch is dirty. Refusing to base semantic version on uncommitted changes

Our current versioning strategy doesn't seem to follow any of the available ATM, but that's another topic. I'm setting it to `None` for now and it's building.

          with:
            versioning: None

A related issue might be that documentation states that _Strategies only work when no custom buildMethod is specified_ but that doesn't seems to be true anymore -didn't really followed the code to see intention-.

Awesome work, BTW, really excited and looking forward into how this action evolves :)

**Comment by webbertakken** [comment]
@ivan-omnidrone Thank you for testing it, and thanks for your compliments.

The error that you are now getting is as designed; Branch is dirty means that you checked out your repository but then changed files after the checkout. It fails for that because it's considered bad practice to let the pipeline change any files (unless if there's a valid reason to do it).

`Versioning: None` will work, but actually I would recommend sticking with the default of `Semantic` unless you already have worked out versioning for your project by yourself.

I'll explain why:

- Incorporating your own versioning scheme can be hard and tedious and takes time away from working on the project itself.
- The option `Semantic` will work out of the box; if you don't do anything, and you have also never set a tag before, the version will be `0.0.257` where `257` is the amount of commits in your repository at the time of your build.
- You can update major and minor versions as simple as creating a tag on your repository. (for example `v1.0` or `v0.1`, then your next build will use version `1.0.0` or `0.1.0` respectively, and increment the last digit for the amount of commits since that tag.
- This will help you easily identify mismatches between server and client (in case they're in the same repository) 
- Lastly, if you use a bug reporting system, the version will act as an identifier, that will be unique for every build (in your case different for your server as for the client, as they are 2 repositories).

The only thing you would have to do is make sure that your repository is not dirty (or we could add a flag that allows for dirty builds).

Don't get me wrong; of course you're free to use the actions as you please. I'm just curious about the use case and whether or not knowing the above you would indeed still choose for `None`. Perhaps we can improve the actions for everyone's sake.

**Comment by webbertakken** [comment]
To come back on your comment about strategies;

> A related issue might be that documentation states that Strategies only work when no custom buildMethod is specified but that doesn't seems to be true anymore -didn't really followed the code to see intention-.

It's still true that they only work with the default buildMethod, or in case you implement a function that applies the version to the build in your custom build method, like illustrated below;

![image](https://user-images.githubusercontent.com/20756439/82558503-13da4180-9b6e-11ea-8f73-446feacd6c45.png)

However there is a pre-build step that determines the version for the build. This pre-build step happens outside of the buildMethod and even before the unity container is started. This is why it failed on this pre-build step for you and not in the build itself. If you have a custom buildMethod, you'll also have to pass the `version` argument into your build, as can be seen [here](https://github.com/webbertakken/unity-builder/blob/master/action/default-build-script/Assets/Editor/Builder.cs#L30).

**Comment by ivan-omnidrone** [comment]
I think you're absolutely right about versioning, and of course we'll need something. Currently we have a build version number in Jenkins and major and minor in Unity. While attempting to get the builds done with Github actions, I was just delaying this problem for a moment, but sounds like the Semantic default will work for us.

About the repo not being clean, our case is that we're cloning the repo and then deleting StreamingAssets folder for Android or iOS depending on which platform are we building. That will show the repo as dirty, but it might be a legit case.

**Comment by webbertakken** [comment]
@ivan-omnidrone I would call that a legit use case indeed. I added the flag for this.

could you test your build once more using `unity-builder@a808c06` with:
```yaml
  allowDirtyBuild: true
```

And versioning set back to the default `Semantic`?

**Comment by ivan-omnidrone** [comment]
Enabling both things worked correctly!
There's an unrelated issue that I'll need to debug in our end.

Thank you!
